apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-test-apps
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 1073741824
    retention.ms: 86400000
    segment.bytes: 1073741824
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-test-apps-reversed
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 1073741824
    retention.ms: 86400000
    segment.bytes: 1073741824
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-test-apps-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Write
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Create
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Describe
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-test-apps-streams
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-test-apps-reversed
        operation: Write
      - resource:
          type: topic
          name: kafka-test-apps-reversed
        operation: Create
      - resource:
          type: topic
          name: kafka-test-apps-reversed
        operation: Describe
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Read
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Describe
      - resource:
          type: group
          name: my-kafka-streams
        operation: Read
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-test-apps-consumer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: my-kafka-consumer
        operation: Read
      - resource:
          type: topic
          name: kafka-test-apps-reversed
        operation: Read
      - resource:
          type: topic
          name: kafka-test-apps-reversed
        operation: Describe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: quay.io/scholzj/quarkus-kafka-producer:latest
          env:
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SECURITY_PROTOCOL
              value: SSL
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_TRUSTSTORE_TYPE
              value: PEM
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_TRUSTSTORE_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.crt
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_TYPE
              value: PEM
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_CERTIFICATE_CHAIN
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-producer
                  key: user.crt
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-producer
                  key: user.key
            - name: MP_MESSAGING_OUTGOING_PRODUCED_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: MP_MESSAGING_OUTGOING_PRODUCED_TOPIC
              value: kafka-test-apps
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-streams
  name: kafka-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-streams
  template:
    metadata:
      labels:
        app: kafka-streams
    spec:
      containers:
        - name: kafka-streams
          image: quay.io/scholzj/quarkus-kafka-streams:latest
          env:
            - name: QUARKUS_KAFKA_STREAMS_SECURITY_PROTOCOL
              value: SSL
            - name: QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_TYPE
              value: PEM
            - name: QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.crt
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_TYPE
              value: PEM
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_CERTIFICATE_CHAIN
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-streams
                  key: user.crt
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-streams
                  key: user.key
            - name: QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: QUARKUS_KAFKA_STREAMS_APPLICATION_ID
              value: my-kafka-streams
          volumeMounts:
            - name: truststore
              mountPath: "/etc/truststore"
              readOnly: true
            - name: keystore
              mountPath: "/etc/keystore"
              readOnly: true
      volumes:
        - name: truststore
          secret:
            secretName: my-cluster-cluster-ca-cert
            items:
              - key: ca.p12
                path: ca.p12
        - name: keystore
          secret:
            secretName: kafka-test-apps-streams
            items:
              - key: user.p12
                path: user.p12
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: quay.io/scholzj/quarkus-kafka-consumer:latest
          env:
            - name: MP_MESSAGING_INCOMING_CONSUMED_SECURITY_PROTOCOL
              value: SSL
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_TRUSTSTORE_TYPE
              value: PEM
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_TRUSTSTORE_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.crt
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_TYPE
              value: PEM
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_CERTIFICATE_CHAIN
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-consumer
                  key: user.crt
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-consumer
                  key: user.key
            - name: MP_MESSAGING_INCOMING_CONSUMED_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: MP_MESSAGING_INCOMING_CONSUMED_TOPIC
              value: kafka-test-apps-reversed
            - name: MP_MESSAGING_INCOMING_CONSUMED_GROUP_ID
              value: my-kafka-consumer
