apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-test-apps-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Write
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Create
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Describe
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-test-apps-consumer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Read
      - resource:
          type: topic
          name: kafka-test-apps
        operation: Describe
      - resource:
          type: group
          name: my-kafka-consumer
        operation: Read
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: scholzj/quarkus-kafka-producer:latest
          env:
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SECURITY_PROTOCOL
              value: SSL
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_TRUSTSTORE_TYPE
              value: PKCS12
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_TRUSTSTORE_LOCATION
              value: /etc/truststore/ca.p12
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.password
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_TYPE
              value: PKCS12
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_LOCATION
              value: /etc/keystore/user.p12
            - name: MP_MESSAGING_OUTGOING_PRODUCED_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-producer
                  key: user.password
            - name: MP_MESSAGING_OUTGOING_PRODUCED_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: MP_MESSAGING_OUTGOING_PRODUCED_TOPIC
              value: kafka-test-apps
          volumeMounts:
            - name: truststore
              mountPath: "/etc/truststore"
              readOnly: true
            - name: keystore
              mountPath: "/etc/keystore"
              readOnly: true
      volumes:
        - name: truststore
          secret:
            secretName: my-cluster-cluster-ca-cert
            items:
              - key: ca.p12
                path: ca.p12
        - name: keystore
          secret:
            secretName: kafka-test-apps-producer
            items:
              - key: user.p12
                path: user.p12
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: scholzj/quarkus-kafka-consumer:latest
          env:
            - name: MP_MESSAGING_INCOMING_CONSUMED_SECURITY_PROTOCOL
              value: SSL
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_TRUSTSTORE_TYPE
              value: PKCS12
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_TRUSTSTORE_LOCATION
              value: /etc/truststore/ca.p12
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.password
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_TYPE
              value: PKCS12
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_LOCATION
              value: /etc/keystore/user.p12
            - name: MP_MESSAGING_INCOMING_CONSUMED_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-test-apps-consumer
                  key: user.password
            - name: MP_MESSAGING_INCOMING_CONSUMED_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: MP_MESSAGING_INCOMING_CONSUMED_TOPIC
              value: kafka-test-apps
            - name: MP_MESSAGING_INCOMING_CONSUMED_GROUP_ID
              value: my-kafka-consumer
          volumeMounts:
            - name: truststore
              mountPath: "/etc/truststore"
              readOnly: true
            - name: keystore
              mountPath: "/etc/keystore"
              readOnly: true
      volumes:
        - name: truststore
          secret:
            secretName: my-cluster-cluster-ca-cert
            items:
              - key: ca.p12
                path: ca.p12
        - name: keystore
          secret:
            secretName: kafka-test-apps-consumer
            items:
              - key: user.p12
                path: user.p12