version: 2.1
jobs:
  build-amd64:
    resource_class: medium
    machine:
      image: ubuntu-2004:202111-01
    environment:
      USER: scholzj
      DOCKER_TAG: latest-amd64
      DOCKER_REGISTRY: ghcr.io
    steps:
      - checkout
      - run:
          name: Build code
          command: make build
      - run:
          name: Build Docker images
          command: make docker_build
      - deploy:
          name: Login to Docker Hub
          command: docker login ghcr.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push to Docker hub
          command: make docker_push
  build-arm64:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:202101-01
    environment:
      USER: scholzj
      DOCKER_TAG: latest-arm64
      DOCKER_REGISTRY: ghcr.io
    steps:
      - checkout
      - run:
          name: Build code
          command: make build
      - run:
          name: Build Docker images
          command: make docker_build
      - deploy:
          name: Login to Docker Hub
          command: docker login ghcr.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push to Docker hub
          command: make docker_push
workflows:
  build-workflow:
    jobs:
      - build-amd64:
            context: ghcr.io
      - build-arm64:
          context: ghcr.io