#!/bin/sh
set +x

if [[ "$TRUSTSTORE_FILE" && "$TRUSTSTORE_PASSWORD_FILE" ]];
then
    if [[ -f $TRUSTSTORE_FILE && -f $TRUSTSTORE_PASSWORD_FILE ]];
    then
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL=SSL
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_TRUSTSTORE_PASSWORD="$(cat $TRUSTSTORE_PASSWORD_FILE)"
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_TRUSTSTORE_TYPE=PKCS12
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_TRUSTSTORE_LOCATION=$TRUSTSTORE_FILE

        # Have to set the KEYSTORE config to dummy values (based on truststore)
        # Otherwise Kafka will complain about the keystore values being set
        # This is a Quarkus limitation of how it deals with configuration :-(
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_PASSWORD="$(cat $TRUSTSTORE_PASSWORD_FILE)"
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_TYPE=PKCS12
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_LOCATION=$TRUSTSTORE_FILE
    fi
fi

if [[ "$KEYSTORE_FILE" && "$KEYSTORE_PASSWORD_FILE" ]];
then
    if [[ -f $KEYSTORE_FILE && -f $KEYSTORE_PASSWORD_FILE ]];
    then
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL=SSL
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_PASSWORD="$(cat $KEYSTORE_PASSWORD_FILE)"
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_TYPE=PKCS12
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SSL_KEYSTORE_LOCATION=$KEYSTORE_FILE
    fi
fi

if [[ "$USERNAME" && "$PASSWORD" ]];
then
    echo "Preparing JAAS configurtion"

    if [[ "$SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL" && "$SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL" == "SSL" ]];
    then
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL=SASL_SSL
    else
        export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SECURITY_PROTOCOL=SASL_PLAINTEXT
    fi

    export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SASL_MECHANISM=SCRAM-SHA-512
    export SMALLRYE_MESSAGING_SINK_TEST_TOPIC_SASL_JAAS_CONFIG="org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${USERNAME}\" password=\"${PASSWORD}\";"
fi

exec $1
